# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QStatusBar, QTextEdit, QWidget)

class Ui_mainMenu(object):
    def setupUi(self, mainMenu):
        if not mainMenu.objectName():
            mainMenu.setObjectName(u"mainMenu")
        mainMenu.resize(480, 636)
        self.centralwidget = QWidget(mainMenu)
        self.centralwidget.setObjectName(u"centralwidget")
        self.title_label = QLabel(self.centralwidget)
        self.title_label.setObjectName(u"title_label")
        self.title_label.setGeometry(QRect(10, 10, 461, 71))
        font = QFont()
        font.setPointSize(15)
        self.title_label.setFont(font)
        self.title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.status_remind_text = QTextEdit(self.centralwidget)
        self.status_remind_text.setObjectName(u"status_remind_text")
        self.status_remind_text.setGeometry(QRect(260, 110, 211, 311))
        font1 = QFont()
        font1.setPointSize(7)
        self.status_remind_text.setFont(font1)
        self.status_remind_text.setAutoFillBackground(False)
        self.status_remind_text.setReadOnly(True)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(260, 90, 191, 16))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 90, 241, 191))
        self.userid_info = QLineEdit(self.groupBox)
        self.userid_info.setObjectName(u"userid_info")
        self.userid_info.setGeometry(QRect(10, 30, 221, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.userid_info.setFont(font2)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 121, 16))
        self.date_info_year = QLineEdit(self.groupBox)
        self.date_info_year.setObjectName(u"date_info_year")
        self.date_info_year.setGeometry(QRect(10, 90, 71, 21))
        font3 = QFont()
        font3.setPointSize(9)
        self.date_info_year.setFont(font3)
        self.date_info_year.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 70, 161, 21))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 120, 101, 20))
        self.emailaddress_info = QLineEdit(self.groupBox)
        self.emailaddress_info.setObjectName(u"emailaddress_info")
        self.emailaddress_info.setGeometry(QRect(10, 140, 221, 31))
        self.emailaddress_info.setFont(font2)
        self.date_info_month = QLineEdit(self.groupBox)
        self.date_info_month.setObjectName(u"date_info_month")
        self.date_info_month.setGeometry(QRect(90, 90, 41, 21))
        self.date_info_month.setFont(font3)
        self.date_info_month.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.date_info_day = QLineEdit(self.groupBox)
        self.date_info_day.setObjectName(u"date_info_day")
        self.date_info_day.setGeometry(QRect(140, 90, 41, 21))
        self.date_info_day.setFont(font3)
        self.date_info_day.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.date_info_hour = QLineEdit(self.groupBox)
        self.date_info_hour.setObjectName(u"date_info_hour")
        self.date_info_hour.setGeometry(QRect(190, 90, 41, 21))
        self.date_info_hour.setFont(font3)
        self.date_info_hour.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 290, 241, 211))
        self.send_report_btn = QPushButton(self.groupBox_2)
        self.send_report_btn.setObjectName(u"send_report_btn")
        self.send_report_btn.setGeometry(QRect(130, 170, 101, 31))
        self.choose_location_btn = QPushButton(self.groupBox_2)
        self.choose_location_btn.setObjectName(u"choose_location_btn")
        self.choose_location_btn.setGeometry(QRect(10, 130, 101, 31))
        self.download_data_btn = QPushButton(self.groupBox_2)
        self.download_data_btn.setObjectName(u"download_data_btn")
        self.download_data_btn.setGeometry(QRect(10, 170, 101, 31))
        self.download_report_btn = QPushButton(self.groupBox_2)
        self.download_report_btn.setObjectName(u"download_report_btn")
        self.download_report_btn.setGeometry(QRect(130, 130, 101, 31))
        self.choose_location_info = QTextEdit(self.groupBox_2)
        self.choose_location_info.setObjectName(u"choose_location_info")
        self.choose_location_info.setGeometry(QRect(10, 30, 221, 91))
        font4 = QFont()
        font4.setPointSize(8)
        self.choose_location_info.setFont(font4)
        self.choose_location_info.setReadOnly(True)
        self.save_path = QLabel(self.groupBox_2)
        self.save_path.setObjectName(u"save_path")
        self.save_path.setGeometry(QRect(10, 10, 54, 16))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(260, 430, 211, 71))
        self.draw_signal_btn = QPushButton(self.groupBox_3)
        self.draw_signal_btn.setObjectName(u"draw_signal_btn")
        self.draw_signal_btn.setGeometry(QRect(10, 10, 71, 24))
        self.log_out_btn = QPushButton(self.groupBox_3)
        self.log_out_btn.setObjectName(u"log_out_btn")
        self.log_out_btn.setGeometry(QRect(130, 10, 71, 24))
        self.callback_btn = QPushButton(self.groupBox_3)
        self.callback_btn.setObjectName(u"callback_btn")
        self.callback_btn.setGeometry(QRect(10, 40, 71, 24))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 510, 120, 81))
        self.suggestion_rdobtn = QRadioButton(self.groupBox_4)
        self.suggestion_rdobtn.setObjectName(u"suggestion_rdobtn")
        self.suggestion_rdobtn.setGeometry(QRect(10, 10, 101, 20))
        self.suggestion_rdobtn.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.push_suggestion_btn = QPushButton(self.groupBox_4)
        self.push_suggestion_btn.setObjectName(u"push_suggestion_btn")
        self.push_suggestion_btn.setEnabled(False)
        self.push_suggestion_btn.setGeometry(QRect(20, 40, 81, 31))
        self.suggestion_textEdit = QTextEdit(self.centralwidget)
        self.suggestion_textEdit.setObjectName(u"suggestion_textEdit")
        self.suggestion_textEdit.setEnabled(False)
        self.suggestion_textEdit.setGeometry(QRect(140, 510, 331, 81))
        mainMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(mainMenu)
        self.statusbar.setObjectName(u"statusbar")
        mainMenu.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(mainMenu)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 480, 22))
        mainMenu.setMenuBar(self.menubar)

        self.retranslateUi(mainMenu)

        QMetaObject.connectSlotsByName(mainMenu)
    # setupUi

    def retranslateUi(self, mainMenu):
        mainMenu.setWindowTitle(QCoreApplication.translate("mainMenu", u"\u4e3b\u754c\u9762", None))
        self.title_label.setText(QCoreApplication.translate("mainMenu", u"textlabel", None))
        self.label_4.setText(QCoreApplication.translate("mainMenu", u"\u72b6\u6001\u63d0\u793a\u680f\uff1a", None))
        self.groupBox.setTitle("")
        self.userid_info.setText("")
        self.label.setText(QCoreApplication.translate("mainMenu", u"\u7ed1\u5b9a\u7528\u6237id", None))
        self.date_info_year.setText("")
        self.date_info_year.setPlaceholderText(QCoreApplication.translate("mainMenu", u"yyyy", None))
        self.label_2.setText(QCoreApplication.translate("mainMenu", u"\u83b7\u53d6\u65e5\u671f(yyyy-mm-dd-hh)", None))
        self.label_3.setText(QCoreApplication.translate("mainMenu", u"\u53d1\u9001\u90ae\u7bb1\u5730\u5740", None))
        self.emailaddress_info.setText("")
        self.date_info_month.setText("")
        self.date_info_month.setPlaceholderText(QCoreApplication.translate("mainMenu", u"mm", None))
        self.date_info_day.setText("")
        self.date_info_day.setPlaceholderText(QCoreApplication.translate("mainMenu", u"dd", None))
        self.date_info_hour.setText("")
        self.date_info_hour.setPlaceholderText(QCoreApplication.translate("mainMenu", u"hh", None))
        self.groupBox_2.setTitle("")
        self.send_report_btn.setText(QCoreApplication.translate("mainMenu", u"\u53d1\u9001\u62a5\u544a", None))
        self.choose_location_btn.setText(QCoreApplication.translate("mainMenu", u"\u9009\u62e9\u672c\u5730\u8def\u5f84", None))
        self.download_data_btn.setText(QCoreApplication.translate("mainMenu", u"\u4e0b\u8f7d\u539f\u59cb\u6570\u636e", None))
        self.download_report_btn.setText(QCoreApplication.translate("mainMenu", u"\u4e0b\u8f7d\u539f\u59cb\u62a5\u544a", None))
        self.choose_location_info.setHtml(QCoreApplication.translate("mainMenu", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">aaa</span></p></body></html>", None))
        self.save_path.setText(QCoreApplication.translate("mainMenu", u"\u4fdd\u5b58\u8def\u5f84", None))
        self.groupBox_3.setTitle("")
        self.draw_signal_btn.setText(QCoreApplication.translate("mainMenu", u"\u67e5\u770b\u4fe1\u53f7", None))
        self.log_out_btn.setText(QCoreApplication.translate("mainMenu", u"\u6ce8\u9500\u767b\u5f55", None))
        self.callback_btn.setText(QCoreApplication.translate("mainMenu", u"\u53cd\u9988", None))
        self.groupBox_4.setTitle("")
        self.suggestion_rdobtn.setText(QCoreApplication.translate("mainMenu", u"\u662f\u5426\u7ed9\u51fa\u5efa\u8bae", None))
        self.push_suggestion_btn.setText(QCoreApplication.translate("mainMenu", u"\u63d0\u4ea4\u5efa\u8bae", None))
    # retranslateUi

